// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEfNvi7fNSK3oGuokaLUIxlbogqvGxvo',
    appId: '1:579171100731:android:f3a68a54b76c99755a941e',
    messagingSenderId: '579171100731',
    projectId: 'zsocial-fe072',
    storageBucket: 'zsocial-fe072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTyF5xRtil7Tgq_uPEAPIFg3EzLGKj7c',
    appId: '1:579171100731:ios:63b2aee84d8b0e5a5a941e',
    messagingSenderId: '579171100731',
    projectId: 'zsocial-fe072',
    storageBucket: 'zsocial-fe072.firebasestorage.app',
    androidClientId: '579171100731-h852o38d10qs665ckuturtjntrvfn3np.apps.googleusercontent.com',
    iosClientId: '579171100731-v39hnraor2aetpr5p53t5h8gmh4qpvuv.apps.googleusercontent.com',
    iosBundleId: 'com.retrytech.bubbly',
  );
}
